version: "3.7"

services:
    telegram-bot-api:
        build:
            context: https://github.com/Dedrimer/telegram-bot-api-docker.git#master
            dockerfile: Dockerfile
            args:
                TELEGRAM_BOT_API_REPOSITORY: "${TELEGRAM_BOT_API_REPOSITORY:-https://github.com/Dedrimer/telegram-bot-api.git}"
                TELEGRAM_BOT_API_REF: "${TELEGRAM_BOT_API_REF:-master}"
                nproc: "${TELEGRAM_BOT_API_BUILD_JOBS:-2}"
        image: telegram-bot-api:local
        environment:
            TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
            TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
            TELEGRAM_LOCAL: "${TELEGRAM_LOCAL}"
        volumes:
            - ${BOT_API_DIR}:/var/lib/telegram-bot-api
        restart: unless-stopped

    bot:
        build:
            context: https://github.com/Dedrimer/telegram-downloader.git#main
            dockerfile: Dockerfile
        image: telegram-downloader:local
        environment:
            LOCAL_BOT_API_URL: "http://telegram-bot-api:8081"
            BOT_API_DIR: "/var/lib/telegram-bot-api/"
            DOWNLOAD_TO_DIR: "./downloads/"
            BOT_TOKEN: "${BOT_TOKEN}"
            USER_ID: "${USER_ID}"
            CHAT_ID: "${CHAT_ID}"
            SINGLE_FILE_GROUP_ENABLED: "${SINGLE_FILE_GROUP_ENABLED:-False}"
            SINGLE_FILE_GROUP_DELAY: "${SINGLE_FILE_GROUP_DELAY:-1.0}"
        volumes:
            - ${DOWNLOAD_TO_DIR}:/app/downloads
            - ${BOT_API_DIR}:/var/lib/telegram-bot-api
        depends_on:
            - telegram-bot-api
        restart: unless-stopped
